### ISSUE TITLE
!mute is unnecessary

### ISSUE THREAD

**Issue by Vindurawr** [sergei-maertens/discord-bot#10]
!mute is not working and is quite redundant since we have mee6 for muting people :)

**Comment by DanHares** [comment]
Is this not for notifications of games your subscribed to.
e.g. if you're subbed to BF1, and you wantto be notified when people start playing.
But you dont want to be notified when BBT starts playing it?

**Comment by sergei-maertens** [comment]
Removed it, you can just unsubscribe as @Vindurawr made clear
