### ISSUE TITLE
!whoinvented command

### ISSUE THREAD

**Issue by DanHares** [sergei-maertens/discord-bot#17]
!whoinvented and it just says 'according to @Gusppetti x was invented by the Romans in Rome

x = Random word
Either submitted like the mutiny bot, or selected form a pre-defined web list

**Comment by sergei-maertens** [comment]
not doing the random word thing, the command takes an argument. Implemented in https://github.com/sergei-maertens/discord-bot/commit/251cf4f35777c96a0213ba6b10c2a44e00d5b9b1
