### ISSUE TITLE
Pull random post from subreddit without adding as custom command first

### ISSUE THREAD

**Issue by DanHares** [sergei-maertens/discord-bot#9]
Ability to have a dynamic (I think that's what it's called) command, so if we do a command like
!dadjokes 
it would pull a random post from that subreddit and post it in discord.

This very similar to what is set up already, but instead of binding the command to a sub first, it can just recognise it's a sub straight away and grab a post.

**Comment by DanHares** [comment]
Here's the path to the code that JoodBot used to execute this, could you use this?

javacord_bot/src/com/unwin/joodbot/commands/subreddit_command.kt

https://github.com/samunwin/javacord_bot/blob/master/src/com/unwin/joodbot/commands/subreddit_command.kt

**Comment by sergei-maertens** [comment]
Implemented it in 0cfc898597f75651d40a1d5a7ad9b201a8e472b7, but I'm a bit weary that it might get too verbose when using other implemented commands. E.g., there's a `!benis` command, if you execute that, it will also fetch the subreddit `benis`. Let's see if it gets annoying
